# Site settings
email: hwarangyyc@gmail.com
url: https://HWARANGyyc.ca/
keywords: "soccer, calgary, alberta, hwarang, korean"
description: "Love Soccer? Dribble, pass, and shoot! Your enthusiasm and talent will inspire us at the KOREA HWARANG football club."

plugins:
  - jekyll-polyglot

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 8aa8a1
  primary-rgb: "138, 168, 161"
  secondary: 2c3e50
  secondary-dark: 233140

# Footer settings
footer:
  copyright: Dr. Henry Jekyll

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
    path: "_posts"
    type: "posts"
    lang: en    
  - scope:
    path: "_posts/ko"
    type: "posts"
    lang: ko

# multilang
languages: ["en", "ko"]
default_lang: "en"
parallel_localization: true
lang_from_path: true
