# Site settings
title: KOREA HWARANG
email: hwarangyyc@gmail.com
url: https://github.com/jeromelachaud/freelancer-theme
keywords: "soccer, calgary, alberta, hwarang, korean"
description: "Love Soccer? Participate, run, and score with your enthusiasm for soccer and inspire others at the Hwarang Football Club."
slogan: "Love Soccer? Dribble, pass, and shoot!<br />Your enthusiasm and talent will inspire us."
meta_author: Alex Seo

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 8aa8a1
  primary-rgb: "138, 168, 161"
  secondary: 2c3e50
  secondary-dark: 233140

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  hours: Hours
  contact: Contact

# Postal address (add as many lines as necessary)
address:
  - line: Genesis Centre
  - line: 7555 Falconridge Blvd NE
  - line: Calgary, AB T3J 0C9
  
# Hours
hours:
  - line: (Usually) Sundays
  - line: 5:30 - 8:30 PM
msg: Contact us prior to visit.

# Contact
contact: '<a href="https://open.kakao.com/o/sGzCGZEe" target="_blank">Kakao OpenChat</a> <br />or<br /><a href="mailto:hwarangyyc@gmail.com">hwarangyyc@gmail.com</a>'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
