lang_name: "English"

title: "KOREA HWARANG"
slogan: "Love Soccer? Dribble, pass, and shoot!<br />Your enthusiasm and talent will inspire us."
about: |
  <p>Korea Hwarang Football Club, simply referred to as Hwarang, is a Sunday league football club based in Calgary, Alberta, Canada. Hwarang was formed in 2014 by a few Koreans, <b>"to promote social activities and friendship among Koreans living in Calgary."</b></p>
  <p>The founding members aimed to offer newcomers the chance to participate in experiences that native Calgarians/Canadians take for granted. In addition, Hwarang promotes social and competitive activities that bring Koreans together for fun and fellowship. Through soccer games and interactions, participants learn about each other, celebrate each other's successes, and are encouraged by other's success in new endeavors.</p>
  <p>Hwarang members welcome anyone who wants to join the club but they only welcome people who share their values - <i>respect</i> and <i>kindness</i> - with the rest of the team. Contact Hwarang today to get started!</p>

subheading:
  about: ABOUT
  news: NEWS
  replay: REPLAY

footer:
  location: Location
  hours: Hours
  contact: Contact

address:
  - line: Genesis Centre
  - line: 7555 Falconridge Blvd NE
  - line: Calgary, AB T3J 0C9

hours:
  - line: (Usually) Sundays
  - line: 5:30 - 8:30 PM
msg: Contact us prior to visit.

contact: '<a href="https://open.kakao.com/o/sGzCGZEe" target="_blank"><img src="img/kakaotalk_icon.png" width="80"></a>&nbsp;&nbsp;&nbsp;<a href="https://www.instagram.com/calgary_hwarangfc" target="_blank"><img src="img/instagram_icon.png" width="80"></a>&nbsp;&nbsp;&nbsp;<a href="mailto:hwarangyyc@gmail.com"><img src="img/gmail_icon.png" width="80"></a>'
