lang_name: "세종대왕 만세"

title: "화랑"
slogan: "축구 좋아하세요?<br />사람이 더 좋은 축구모임 화랑 입니다!"
about: |
  <p>안녕하세요! 캘거리 한인 축구팀 화랑입니다.</p>
  <p>우리 화랑은 20-40대까지 건강한 남성들이 모여 즐거운 분위기로 운동을 하는 팀입니다. 매주 일요일 실내구장에서 풋살 혹은 야외에서 축구를 하고있습니다. 즐거운 분위기로 함께 운동하실 새로운 팀원을 모집합니다!</p>
  <p>차량편 공유도 가능하오니 아래 연락처로 문의주시면 자세히 안내 드리도록 하겠습니다. 많은 관심 부탁드립니다. 감사합니다 :)</p>

subheading:
  about: "회원 모집"
  news: "화랑 소식"
  replay: "하이라이트"

footer:
  location: "모임장소"
  hours: "운영시간"
  contact: "연락처"

address:
  - line: "제네시스센터"
  - line: 7555 Falconridge Blvd NE
  - line: Calgary, AB T3J 0C9

hours:
  - line: "매주 일요일"
  - line: "오후 5:30 - 8:30"
msg: "공지 없이 변동될 수 있습니다."

contact: '<a href="https://open.kakao.com/o/sGzCGZEe" target="_blank"><img src="img/kakaotalk_icon.png" width="80"></a>&nbsp;&nbsp;&nbsp;<a href="https://www.instagram.com/calgary_hwarangfc" target="_blank"><img src="img/instagram_icon.png" width="80"></a>&nbsp;&nbsp;&nbsp;<a href="mailto:hwarangyyc@gmail.com"><img src="img/gmail_icon.png" width="80"></a>'
